name: Gabriel Tomescu
favicon: null
layout_spectrum: 0.4458282603882253
typography_spectrum: 0.5042205390054733
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5796962724998593
  lightness: 0.6587517231237143
  saturation: 0.2661635549739003
  rhythmicContrast: 0.7081410998944193
purpose: []
